apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: profiles.compliance.openshift.io
spec:
  group: compliance.openshift.io
  names:
    kind: Profile
    listKind: ProfileList
    plural: profiles
    singular: profile
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: Profile is the Schema for the profiles API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        description:
          type: string
        id:
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        rules:
          items:
            description: ProfileRule defines the name of a specific rule in the profile
            type: string
          nullable: true
          type: array
        title:
          type: string
        values:
          items:
            description: ProfileValue defines a value for a setting in the profile
            type: string
          nullable: true
          type: array
      required:
      - description
      - id
      - title
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
