kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: compliance-profile-operator
subjects:
- kind: ServiceAccount
  name: compliance-profile-operator
roleRef:
  kind: Role
  name: compliance-profile-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: profileparser
subjects:
- kind: ServiceAccount
  name: profileparser
roleRef:
  kind: Role
  name: profileparser
  apiGroup: rbac.authorization.k8s.io